// token.h
#ifndef TOKEN_H
#define TOKEN_H

// Basic ennumeration of SQL tokens
enum class TokenType {
    // KEYWORDS
    TOKEN_KEYWORD_SELECT,   // SELECT
    TOKEN_KEYWORD_FROM, // FROM
    TOKEN_KEYWORD_WHERE,    // WHERE
    TOKEN_KEYWORD_INSERT,   // INSERT
    TOKEN_KEYWORD_INTO, // INTO
    TOKEN_KEYWORD_VALUES,   // VALUES
    TOKEN_KEYWORD_CREATE,   // CREATE
    TOKEN_KEYWORD_TABLE,    // TABLE
    TOKEN_KEYWORD_DELETE,   // DELETE
    TOKEN_KEYWORD_UPDATE,   // UPDATE
    TOKEN_KEYWORD_SET,  // SET
    TOKEN_KEYWORD_BEGIN,    // BEGIM
    TOKEN_KEYWORD_COMMIT,   // COMMIT
    TOKEN_KEYWORD_ROLLBACK, // ROLLBACK
    TOKEN_KEYWORD_INDEX,    // INDEX
    TOKEN_KEYWORD_ON,   // ON
    TOKEN_KEYWORD_NULL, // NULL

    // OPERATORS
    TOKEN_OPERATOR_EQUAL,   // =
    TOKEN_OPERATOR_DIFFERENT, // !=
    TOKEN_OPERATOR_NOT_EQUAL,   // <>
    TOKEN_OPERATOR_LESS_THAN,   // <
    TOKEN_OPERATOR_GREATER_THAN, // >
    TOKEN_OPERATOR_LESS_THAN_OR_EQUAL,  // <=
    TOKEN_OPERATOR_GREATER_THAN_OR_EQUAL, // >=
    TOKEN_OPERATOR_AND, // AMD
    TOKEN_OPERATOR_OR,  // OR
    TOKEN_OPERATOR_NOT, // NOT
    TOKEN_OPERATOR_PLUS, // +
    TOKEN_OPERATOR_MINUS,   // -
    TOKEN_OPERATOR_MULTIPLY,    // *
    TOKEN_OPERATOR_DIVIDE,  // /
    TOKEN_OPERATOR_LIKE, // LIKE
    TOKEN_OPERATOR_IN,  // IN
    TOKEN_OPERATOR_BETWEEN, // BETWEEN
    TOKEN_OPERATOR_IS_NULL  // IS NULL
};

// Token Structure
typedef struct {
    TokenType type; // Token type
    char * lexeme;  // string that represents token
} Token;

#endif // TOKEN_H
